# Site settings
title: 假正经的博客                                                  # 博客的标题
SEOTitle: 假正经的博客                                   # 显示在浏览器上搜索的时候显示的标题
header-img: img/post-index-img.jpg                                # 显示在首页的背景图片
email: 13617937161@163.com                                       # 邮箱地址
description: "不积跬步，无以至千里."           # 网站介绍
keyword: "假正经的博客, fakeserious.github.io, fakeserious, fakeSerious, 假正经, 大数据"     # 关键词
url: "https://fakeserious.github.io/"                             # 博客的地址
baseurl: ""                                                        # 博客的托管地址

# Publish posts or collection documents with a future date.
future: true                                                       #发布未来日期的文档。

# SNS settings
RSS: false
github_username:    fakeSerious

# Build settings
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # 如果想自定义anchor。查看post.html的181行
# 如果在中国有时区问题（例如＃68），请取消注释以使用此选项：
timezone: Asia/Shanghai


# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
# 从2016年开始，GitHub页面上不支持'pygments'，使用'rouge'代替突出显示。
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Gitalk
#gitalk:
#  enable: true                                              #是否开启Gitalk评论
#  clientID: 35868e6b4c40c05c1512                            #生成的clientID
#  clientSecret: 2adebe65502a2922717e15e81d368c2feb111485    #生成的clientSecret
#  repo: zhangweisep.github.io                              #仓库名称
#  owner: ZhangWeiSep                                       #github用户名
#  admin: ZhangWeiSep
#  distractionFreeMode: true                                 #是否启用类似FB的阴影遮罩

# Netease settings
netease_comment: false

# 访问统计
# Analytics settings
# Google Analytics
ga_track_id: 'UA-135441379-1'            # Format: UA-xxxxxx-xx
ga_domain: auto                          # 自定义的域名，默认的是 auto


# Sidebar settings
sidebar: true                           # 是否使用侧边栏
sidebar-about-description: "You make my heart smile<br>学技术,应当自上而下,先窥其全貌,再探其细节"
sidebar-avatar: /img/collect_money.png      # 侧边栏头像图片


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页


# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false


# Friends
friends: [
{
  title: "GitHub",
  href: "https://github.com"
}]
